# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ebb5b997dcd3b7368d3fe192cf236b4f0f14ffe1c0e0a23120cc0ce8f8eb700bbde4ebe88ed83480433893a37b24cdff3596ba138cf5720cceabfc5b1d74056e

test:
  secret_key_base: 45c60f6472ff9c5ef4e40ba28cf7246351353e819e72b13e7c5c72c2d4fffadf76502ba90dc3f287407783921d6867d56fdea12ce4de4ee2fce069acfc12b585

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
